apps/portfolio/urls.py
from django.urls import path, include
from . import views
from apps.authentication.views import signup, login, profile
from django.contrib.auth.views import LogoutView

app_name = 'blog'




urlpatterns = [
    # path('<int:pk>/api-contacts/', views.contact_detail),
    path('api-auth/', include('rest_framework.urls',  namespace='rest_framework')),
    path('', views.home, name='home'),
    path('<int:pk>/post/', views.post, name='post'),
    path('categories/', views.category, name='category'),
    path('category/', views.category_pages, name='category_page'),
    # about us page
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("profile/", profile, name='profile')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.portfolio.urls")),
    path('api/', include("apps.portfolio_api.urls")),
    path('dashboard/', include("apps.dashboard.urls")),
    path('api-auth/', include('rest_framework.urls')),
]


handler404 = "apps.portfolio.views.error_404"
handler500 = "apps.portfolio.views.error_500"

templates/pages/about.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}about us{% endblock title %}


{% block content %}

<style>
	  @import url('https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap');
	* {
	  padding: 0;
	  margin: 0
  }
  
  body {
	overflow-y: hidden !important;
  }
  
  .prifix_loading_box {
	  position: relative;
	  width: 200px;
	  height: 40px;
	  display: flex;
	  align-items: center;
	  justify-content: space-evently
  }
  
  .prifix_loading_box span {
	  display: block;
	  height: 20px;
	  width: 20px;
	  background: green;
	  border-radius: 50%;
	  animation: all-effect 0.6s linear infinite alternate;
	  transform: scale(0)
  }
  
  .prifix_loading_box span:nth-child(1) {
	  animation-delay: 0.1s
  }
  
  .prifix_loading_box span:nth-child(2) {
	  animation-delay: 0.2s
  }
  
  .prifix_loading_box span:nth-child(3) {
	  animation-delay: 0.3s
  }
  
  .prifix_loading_box span:nth-child(4) {
	  animation-delay: 0.4s;
	  background: #00b9f5
  }
  
  .prifix_loading_box span:nth-child(5) {
	  animation-delay: 0.5s;
	  background: #00b9f5
  }
  
  @keyframes all-effect {
	  100% {
		  transform: scale(1)
	  }
  }
  .loader {
	position: relative;
	top: 0% !important;
	z-index: 10 !important;  
  }
  .child {
	position: absolute;
	width: 100%;
	height: 100vh;
	background-color: rgba(1, 1, 1, 0.9);
	top: 50%;
	display: flex;
	justify-content: center;
	align-items: center;
  }
  @media(max-width: 500px) {
	.child {
	  position: absolute;
	  top: 50%;
	}
  }
  .mariana {
	display: none !important;
  }
  .content{
	position: relative;
  }
  .overflow {
	overflow-y: scroll !important;
  }
  @media(max-width: 900px) {
  .beta {
    top: 9.10% !important; 
    z-index: 3 !important;
    /*width: 100%;*/
    border: 2px solid aqua;
    letter-spacing: 2px;
  }
}

.beta span {
   animation: beta_anime 2s linear infinite alternate;
}

.beta span:nth-child(1) {
    animation-delay: 0.1s;
    /*color: white !important;*/
}
.beta span:nth-child(2) {
    animation-delay: 0.2s;
    /*color: blue;*/
}
.beta span:nth-child(3) {
    animation-delay: 0.3s;
    /*color: yellow;*/
}
.beta span:nth-child(4) {
    animation-delay: 0.4;
    /*color: red;*/
}
@keyframes beta_anime {
  50% {
    color: red;
  }
  100% {
    color: aqua;
  }
}
</style>


<div class="d-flex justify-content-center align-items-center loader">
	<div class="prifix_loading_box child"> <span></span> <span></span> <span></span> <span></span> <span></span> </div>
  </div>

<header
  class="masthead"
  style="background-image: url({% static 'assets/img/about.jpg' %})"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>About us</h1>
          <span class="subheading">Designetes for specific about us page</span>
          <!-- <h3 style="
          position: fixed;
          right: 0px !important;
          top:50%;
          background-color: rgba(0, 0, 0, 0.5);
          padding: 10px;
          border: 2px solid aqua;
          font-family: 'Dancing Script', cursive;
          " class="beta"><span>B</span><span>e</span><span>t</span><span>a</span></h3> -->
        </div>
      </div>
    </div>
  </div>
</header>
<!-- ============================ Page Title End ================================== -->

<!-- ============================ Our Story Start ================================== -->
<section>

	<div class="container">
	
		<!-- row Start -->
		<div class="row align-items-center">

			<div class="col-lg-6 col-md-6">
				<div class="story-wrap explore-content">
					
					<span class="ipn-subtitle">About Me</span>
					<h2>IT Mentor, Blogger</h2>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
					
				</div>
			</div>

			
			<div class="col-lg-6 col-md-6 img">
				<img src="{% static 'assets/img/about_2.jpg' %}" class="img-fluid" alt="" />
			</div>
			
		</div>
		<!-- /row -->					
		
	</div>
			
</section>
<!-- ============================ Our Story End ================================== -->	

<script>
	let loader = document.querySelector(".loader")
	let content = document.querySelector(".content")
	window.addEventListener("load", () => {
	  loader.classList.add("mariana")
	  document.body.classList.add("overflow")
	})
  </script>

{% endblock content %}

templates/pages/category_cards.html
{% extends 'layouts/base.html' %} {% block title %}categories{% endblock title %} {% block content %}
{% load static %}
<style>
body {
    overflow-x: hidden;
    overflow-y: hidden !important;
}

.prifix_loading_box {
    position: relative;
    width: 200px;
    height: 40px;
    display: flex;
    align-items: center;
    justify-content: space-evently
}

header {
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
}

.prifix_loading_box span {
    display: block;
    height: 20px;
    width: 20px;
    background: green;
    border-radius: 50%;
    animation: all-effect 0.6s linear infinite alternate;
    transform: scale(0)
}

.prifix_loading_box span:nth-child(1) {
    animation-delay: 0.1s
}

.prifix_loading_box span:nth-child(2) {
    animation-delay: 0.2s
}

.prifix_loading_box span:nth-child(3) {
    animation-delay: 0.3s
}

.prifix_loading_box span:nth-child(4) {
    animation-delay: 0.4s;
    background: #00b9f5
}

.prifix_loading_box span:nth-child(5) {
    animation-delay: 0.5s;
    background: #00b9f5
}

@keyframes all-effect {
    100% {
        transform: scale(1)
    }
}

.loader {
    position: relative;
    top: 0% !important;
    z-index: 10 !important;
}

.child1 {
    position: absolute;
    width: 100%;
    height: 100vh;
    background-color: rgba(1, 1, 1, 0.9);
    top: 50%;
    display: flex;
    justify-content: center;
    align-items: center;
}

@media(max-width: 500px) {
    .child {
        position: absolute;
        top: 50%;
    }
}

.mariana {
    display: none !important;
}

.content {
    position: relative;
}

.overflow {
    overflow-y: scroll !important;
}

.card {
    background-color: #fff;
    border-radius: 10px;
    border: none;
    position: relative;
    margin-bottom: 30px;
    box-shadow: 0 0.46875rem 2.1875rem rgba(90, 97, 105, 0.1),
        0 0.9375rem 1.40625rem rgba(90, 97, 105, 0.1),
        0 0.25rem 0.53125rem rgba(90, 97, 105, 0.12),
        0 0.125rem 0.1875rem rgba(90, 97, 105, 0.1);
}

h2 {
    font-size: 17px !important;
}

h5 {
    font-size: 20px !important;
}

.card .card-statistic-3 .card-icon-large .fas,
.card .card-statistic-3 .card-icon-large .far,
.card .card-statistic-3 .card-icon-large .fab,
.card .card-statistic-3 .card-icon-large .fal {
    font-size: 110px !important;
}

.card .card-statistic-3 .card-icon {
    text-align: center;
    line-height: 50px;
    margin-left: 15px;
    color: #000;
    position: absolute;
    right: -5px;
    top: 20px;
    opacity: 0.1;
    font-size: 100px;
}

.l-bg-cyan {
    background: linear-gradient(135deg, #289cf5, #84c0ec) !important;
    color: #fff;
}

.l-bg-green {
    background: linear-gradient(135deg, #23bdb8 0%, #43e794 100%) !important;
    color: #fff;
}

.l-bg-orange {
    background: linear-gradient(to right, #f9900e, #ffba56) !important;
    color: #fff;
}

.l-bg-cyan {
    background: linear-gradient(135deg, #289cf5, #84c0ec) !important;
    color: #fff;
}

@media(min-width: 992px) {
    .card_bg {
        width: 220px !important;
    }
}

@media(max-width: 500px) {
    header.masthead {
        margin-bottom: 0.5px !important;
    }

    .card_big {
        margin-bottom: 30px !important;
    }
}

.card_big {
    margin-left: auto;
    margin-right: auto;
}

row {
    width: 1200px !important;
    display: flex !important;
    justify-content: center !important;
}

.card_link {
    color: #fff;
    text-decoration: none;
}

.card_link:hover {
    color: white !important;
}

.card_bg {
    width: 200px !important;
    height: 110px !important;
}

.child {
    width: 100% !important;
    height: 100% !important;
    background-color: #555 !important;
    background-blend-mode: multiply;
    background-position: center !important;
    background-size: 100%;
    background-repeat: no-repeat;
    transition: all .5s !important;
}

.card_bg:hover .child,
.card_bg:focus .child {
    background-size: 120%;
    transition: all .5s !important;
}
</style>
<div class="d-flex justify-content-center align-items-center loader">
    <div class="prifix_loading_box child1"> <span></span> <span></span> <span></span> <span></span> <span></span> </div>
</div>
<header class="masthead" style="background-image: url({% static 'assets/img/about.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Category</h1>
                    <span class="subheading">{{ post.sub_heading }}</span>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="col-md-10 card_big">
    <div class="row align-items-center justify-content-center">
        {% for cat in categories %}
        <div class="col-xl-3 col-lg-6 card_bg mb-2">
            <div class="card child" style="background-image: url({{ cat.image.url }});">
                <a class="card_link" href="{% url 'blog:category_page' %}?category={{ cat.name }}">
                    <div class="card-statistic-3 p-4">
                        <div class="row align-items-center mb-2 d-flex">
                            <h2 class="text-center pt-3">{{ cat.name }}</h2>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script>
let loader = document.querySelector(".loader")
let content = document.querySelector(".content")
window.addEventListener("load", () => {
    loader.classList.add("mariana")
    document.body.classList.add("overflow")
})
</script>
{% endblock content %}

templates/pages/category_pages.html
{% extends 'layouts/base.html' %} {% block title %}pages categories{% endblock title %}
{% load static %}
{% block content %}
<style>
    @import url("https://fonts.googleapis.com/css2?family=Baloo+2&display=swap");
/* This pen */
html {
  scroll-behavior: smooth;
}
body {
  font-family: "Baloo 2", cursive;
  font-size: 16px;
  color: #ffffff;
  text-rendering: optimizeLegibility;
  font-weight: initial;
  overflow-y: hidden !important;
}
.dark {
  background: #110f16;
}
header {
      height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
}
.light {
  background: #f3f5f7;
}
a, a:hover {
  text-decoration: none;
  transition: color 0.3s ease-in-out;
}
#pageHeaderTitle {
  margin: 2rem 0;
  text-transform: uppercase;
  text-align: center;
  font-size: 2.5rem;
}
/* Cards */
.postcard {
  flex-wrap: wrap;
  display: flex;
  box-shadow: 0 4px 21px -12px rgba(0, 0, 0, 0.66);
  border-radius: 10px;
  margin: 0 0 2rem 0;
  overflow: hidden;
  position: relative;
  color: #ffffff;
}
.postcard.dark {
  background-color: #18151f;
}
.postcard.light {
  background-color: #e1e5ea;
}
.postcard .t-dark {
  color: #18151f;
}
.postcard a {
  color: inherit;
}
.postcard h1, .postcard .h1 {
  margin-bottom: 0.5rem;
  font-weight: 500;
  line-height: 1.2;
}
.postcard .small {
  font-size: 80%;
}
.postcard .postcard__title {
  font-size: 1.75rem;
}
.postcard .postcard__img {
  max-height: 180px;
  width: 100%;
  object-fit: cover;
  position: relative;
}
.postcard .postcard__img_link {
  display: contents;
}
.postcard .postcard__bar {
  width: 50px;
  height: 10px;
  margin: 10px 0;
  border-radius: 5px;
  background-color: #424242;
  transition: width 0.2s ease;
}
.postcard .postcard__text {
  padding: 1.5rem;
  position: relative;
  display: flex;
  flex-direction: column;
}
.postcard .postcard__preview-txt {
  overflow: hidden;
  text-overflow: ellipsis;
  text-align: justify;
  height: 100%;
}
.postcard .postcard__tagbox {
  display: flex;
  flex-flow: row wrap;
  font-size: 14px;
  margin: 20px 0 0 0;
  padding: 0;
  justify-content: center;
}
.postcard .postcard__tagbox .tag__item {
  display: inline-block;
  background: rgba(83, 83, 83, 0.4);
  border-radius: 3px;
  padding: 2.5px 10px;
  margin: 0 5px 5px 0;
  cursor: default;
  user-select: none;
  transition: background-color 0.3s;
}
.postcard .postcard__tagbox .tag__item:hover {
  background: rgba(83, 83, 83, 0.8);
}
.postcard:before {
  content: "";
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-image: linear-gradient(-70deg, #424242, transparent 50%);
  opacity: 1;
  border-radius: 10px;
}
.postcard:hover .postcard__bar {
  width: 100px;
}
@media screen and (min-width: 769px) {
  .postcard {
    flex-wrap: inherit;
  }
  .postcard .postcard__title {
    font-size: 2rem;
  }
  .postcard .postcard__tagbox {
    justify-content: start;
  }
  .postcard .postcard__img {
    max-width: 300px;
    max-height: 100%;
    transition: transform 0.3s ease;
  }
  .postcard .postcard__text {
    padding: 3rem;
    width: 100%;
  }
  .postcard .media.postcard__text:before {
    content: "";
    position: absolute;
    display: block;
    background: #18151f;
    top: -20%;
    height: 130%;
    width: 55px;
  }
  .postcard:hover .postcard__img {
    transform: scale(1.1);
  }
  .postcard:nth-child(2n+1) {
    flex-direction: row;
  }
  .postcard:nth-child(2n+0) {
    flex-direction: row-reverse;
  }
  .postcard:nth-child(2n+1) .postcard__text::before {
    left: -12px !important;
    transform: rotate(4deg);
  }
  .postcard:nth-child(2n+0) .postcard__text::before {
    right: -12px !important;
    transform: rotate(-4deg);
  }
}
@media screen and (min-width: 1024px) {
  .postcard__text {
    padding: 2rem 3.5rem;
  }
  .postcard__text:before {
    content: "";
    position: absolute;
    display: block;
    top: -20%;
    height: 130%;
    width: 55px;
  }
  .postcard.dark .postcard__text:before {
    background: #18151f;
  }
  .postcard.light .postcard__text:before {
    background: #e1e5ea;
  }
}
/* COLORS */
.postcard .postcard__tagbox .green.play:hover {
  background: #79dd09;
  color: black;
}
.green .postcard__title:hover {
  color: #79dd09;
}
.green .postcard__bar {
  background-color: #79dd09;
}
.green::before {
  background-image: linear-gradient(-30deg, rgba(121, 221, 9, 0.1), transparent 50%);
}
.green:nth-child(2n)::before {
  background-image: linear-gradient(30deg, rgba(121, 221, 9, 0.1), transparent 50%);
}
.postcard .postcard__tagbox .blue.play:hover {
  background: #0076bd;
}
.blue .postcard__title:hover {
  color: #0076bd;
}
.blue .postcard__bar {
  background-color: #0076bd;
}
.blue::before {
  background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 50%);
}
.blue:nth-child(2n)::before {
  background-image: linear-gradient(30deg, rgba(0, 118, 189, 0.1), transparent 50%);
}
.postcard .postcard__tagbox .red.play:hover {
  background: #bd150b;
}
.red .postcard__title:hover {
  color: #bd150b;
}
.red .postcard__bar {
  background-color: #bd150b;
}
.red::before {
  background-image: linear-gradient(-30deg, rgba(189, 21, 11, 0.1), transparent 50%);
}
.red:nth-child(2n)::before {
  background-image: linear-gradient(30deg, rgba(189, 21, 11, 0.1), transparent 50%);
}
.postcard .postcard__tagbox .yellow.play:hover {
  background: #bdbb49;
  color: black;
}
.yellow .postcard__title:hover {
  color: #bdbb49;
}
.yellow .postcard__bar {
  background-color: #bdbb49;
}
.yellow::before {
  background-image: linear-gradient(-30deg, rgba(189, 187, 73, 0.1), transparent 50%);
}
.yellow:nth-child(2n)::before {
  background-image: linear-gradient(30deg, rgba(189, 187, 73, 0.1), transparent 50%);
}
@media screen and (min-width: 769px) {
  .green::before {
    background-image: linear-gradient(-80deg, rgba(121, 221, 9, 0.1), transparent 50%);
  }
  .green:nth-child(2n)::before {
    background-image: linear-gradient(80deg, rgba(121, 221, 9, 0.1), transparent 50%);
  }
  .blue::before {
    background-image: linear-gradient(-80deg, rgba(0, 118, 189, 0.1), transparent 50%);
  }
  .blue:nth-child(2n)::before {
    background-image: linear-gradient(80deg, rgba(0, 118, 189, 0.1), transparent 50%);
  }
  .red::before {
    background-image: linear-gradient(-80deg, rgba(189, 21, 11, 0.1), transparent 50%);
  }
  .red:nth-child(2n)::before {
    background-image: linear-gradient(80deg, rgba(189, 21, 11, 0.1), transparent 50%);
  }
  .yellow::before {
    background-image: linear-gradient(-80deg, rgba(189, 187, 73, 0.1), transparent 50%);
  }
  .yellow:nth-child(2n)::before {
    background-image: linear-gradient(80deg, rgba(189, 187, 73, 0.1), transparent 50%);
  }
}

.prifix_loading_box {
  position: relative;
  width: 200px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: space-evently
}

.prifix_loading_box span {
  display: block;
  height: 20px;
  width: 20px;
  background: green;
  border-radius: 50%;
  animation: all-effect 0.6s linear infinite alternate;
  transform: scale(0)
}

.prifix_loading_box span:nth-child(1) {
  animation-delay: 0.1s
}

.prifix_loading_box span:nth-child(2) {
  animation-delay: 0.2s
}

.prifix_loading_box span:nth-child(3) {
  animation-delay: 0.3s
}

.prifix_loading_box span:nth-child(4) {
  animation-delay: 0.4s;
  background: #00b9f5
}

.prifix_loading_box span:nth-child(5) {
  animation-delay: 0.5s;
  background: #00b9f5
}

@keyframes all-effect {
  100% {
      transform: scale(1)
  }
}
.loader {
position: relative;
top: 0% !important;
z-index: 10 !important;  
}
.child {
position: absolute;
width: 100%;
height: 100vh;
background-color: rgba(1, 1, 1, 0.9);
top: 50%;
display: flex;
justify-content: center;
align-items: center;
}
@media(max-width: 500px) {
.child {
  position: absolute;
  top: 50%;
}
}
.mariana {
display: none !important;
}
.content{
position: relative;
}
.overflow {
overflow-y: scroll !important;
}

</style>

<div class="d-flex justify-content-center align-items-center loader">
  <div class="prifix_loading_box child"> <span></span> <span></span> <span></span> <span></span> <span></span> </div>
</div>

<header class="masthead" style="background-image: url({% static 'assets/img/about.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7" style="width: 900px !important;">
          <div class="site-heading">
            <h1>Specific Pages</h1>
            <span class="subheading">Scroll to read specified <a style="color: white; border-bottom: 2px solid #fff; padding-bottom: 5px;" href="#cards"><strong>categories</strong></a></span>
          </div>
        </div>
      </div>
    </div>
  </header>

<section class="light" id="cards">
  <div class="container py-2">
    {% for post in posts %}
    <article class="postcard light blue">
      <a class="postcard__img_link" href="#">
        {% if post.image %}
            <img
            class="postcard__img"
            src="{{ post.image.url }}"
            alt="Image Title"
        />
        {% endif %}
      </a>
      <div class="postcard__text t-dark" style="padding-left: -30px;">
        <h5 style="transform: translateX(5px);">{{ post.category }}</h5>
        <h1 style="transform: translateX(5px);" class="postcard__title blue"><a href="#">{{ post.post_heading_1 }}</a></h1>
        <div class="postcard__subtitle small">
        </div>
        <div class="postcard__bar"></div>
        <div class="postcard__preview-txt">
          {{ post.post_text_1 }}
        </div>
        <ul class="postcard__tagbox">
          <li class="tag__item"><i class="fas fa-tag mr-2"></i>{{ post.name_blog }}</li>
          <li class="tag__item"><i class="fas fa-clock mr-2"></i>{{ post.min_read }}min</li>
          <li class="tag__item play blue">
            <a href="{% url 'blog:post' post.pk %}"></i>Read more..</a>
          </li>
        </ul>
      </div>
    </article>
    {% endfor %}
  </div>
</section>

<script>
  let loader = document.querySelector(".loader")
  let content = document.querySelector(".content")
  window.addEventListener("load", () => {
    loader.classList.add("mariana")
    document.body.classList.add("overflow")
  })
</script>
{% endblock content %}

templates/pages/home.html
{% extends 'layouts/base.html' %} {% block title %}base page{% endblock title %}
{% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<main id="main_home">
    
    <!-- Page Header-->
    {% for y in homeContents %}
    <header class="masthead" style="background-image: url({{ y.blog_headingImage.url }});">
        {% include 'includes/loader.html' %}
        <div class="profile_tab">
            <div class="profile_nav">
                <p>Campus</p>
                <p><a href="#">Signout</a></p>
            </div>
            <div class="profile_body">
                <img src="{{ user.profile.image.url }}" alt="" width="100">
                <div>
                    <p>{{ user.first_name }}</p>
                    <p>{{ user.email }}</p>
                    <p><a href="#">Switch account</a></p>
                    <p><a href="#">Edit account</a></p>
                </div>
            </div>
            <div class="profile_below">
                <a href="#">Sign in with different account</a>
            </div>
        </div>
        <div class="container  px-4 px-lg-5 sferma">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1 style="color: white !important; position: relative;">{{ y.blog_heading }}</h1>
                        <span class="subheading" style="position: relative;">{{ y.blog_subheading }}</span>
                        <!--  <h3 style="
          position: fixed;
          right: 0px !important;
          top:50%;
          background-color: rgba(0, 0, 0, 0.5);
          padding: 10px;
          border: 2px solid aqua;
          font-family: 'Dancing Script', cursive;
          " class="beta"><span>B</span><span>e</span><span>t</span><span>a</span></h3> -->
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endfor %}
    <!-- Main Content-->
    <div class="container px-4 px-lg-5 content">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7 thing">
                {% for p in posts %}
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{% url 'blog:post' p.pk %}">
                        <h2 class="post-title">
                            {{ p.main_heading }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ p.sub_heading }}
                        </h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">Khusan Akhmedov</a>
                        on {{ p.date_post }}
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
                {% endfor %}
                <!-- Pager-->
                <div class="d-flex justify-content-end mb-4">
                    <a class="btn btn-primary text-uppercase" href="{% url 'blog:category' %}?category/all_posts/34hk4h3kj4hk3j4hkhjkh3k434/">All Posts →</a>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/home.js' %}"></script>
</main>
{% endblock content %}