apps/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
	path("", views.dashboard, name='dashboard_home'),
	path("create-user/", views.create_user, name='create_user')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.portfolio.urls")),
    path('api/', include("apps.portfolio_api.urls")),
    path('dashboard/', include("apps.dashboard.urls")),
    path('api-auth/', include('rest_framework.urls')),
]


handler404 = "apps.portfolio.views.error_404"
handler500 = "apps.portfolio.views.error_500"

apps/dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from apps.portfolio.models import Post
from apps.portfolio.models import Contact
from apps.authentication.forms import CreateUserForm

Users = get_user_model()


def dashboard(request):
    users = Users.objects.count()
    posts = Post.objects.count()
    contact = Contact.objects.count()
    contact_objects = Contact.objects.all()
    all_users = Users.objects.all().order_by('id')[:10]
    complaints = Contact.objects.filter(contact_choices='SHIKOYAT').count()
    offers = Contact.objects.filter(contact_choices='TAKLIF').count()
    context = {
        "users": users,
        "posts": posts,
        "contact": contact,
        "all_users": all_users,
        "contact_objects": contact_objects,
        "complaints": complaints,
        "offers": offers
    }
    return render(request, 'dashboard/pages/dashboard.html', context)


# create user
def create_user(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/dashboard/")
    return render(request, 'dashboard/pages/create_user.html', {"form": form})

templates/dashboard/pages/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}dashboard - {% endblock title %}</title>
</head>

<body>
    {% include 'dashboard/includes/navbar.html' %}
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

templates/dashboard/pages/create_user.html
{% extends 'dashboard/pages/base.html' %}
{% block title %}create user{% endblock title %}
{% block content %}
<form method="post" style="width: 50%; margin-left: auto; margin-right: auto; margin-top: 30px;">
    {% load widget_tweaks %}
    {% csrf_token %}
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Name</label>
        {% render_field form.first_name type="text" class="form-control" placeholder="First Name" %}
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="exampleInputlast" class="form-label">Last name</label>
        {% render_field form.last_name type="text" class="form-control" placeholder="Last Name" %}
    </div>
    <div class="mb-3">
        <label for="exampleInputlast" class="form-label">Email</label>
        {% render_field form.email type="email" class="form-control" placeholder="Email" %}
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        {% render_field form.password1 type="password" class="form-control" placeholder="Password" %}
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword2" class="form-label">Confirm Password</label>
        {% render_field form.password2 type="password" class="form-control" placeholder="Confirm password" %}
    </div>
    <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

templates/dashboard/pages/dashboard.html
{% extends 'dashboard/pages/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
<div class="container">
    <div class="heading">
        <h1>Main stats:</h1>
    </div>
    <div class="main-stats">
        <div class="stats">
            <p>Total Users:</p>
            <h1>{{ users }}</h1>
        </div>
        <!-- <hr> -->
        <div class="stats">
            <p>Total Posts:</p>
            <h1>{{ posts }}</h1>
        </div>
        <!-- <hr> -->
        <div class="stats">
            <p>Total messages:</p>
            <h1>{{ contact }}</h1>
        </div>
        <div class="stats">
            <p>Total complaint messages:</p>
            <h1>{{ complaints }}</h1>
        </div>
        <div class="stats">
            <p>Total offer messages:</p>
            <h1>{{ offers }}</h1>
        </div>
        <div class="stats">
            <p>Something here:</p>
            <h1></h1>
        </div>
    </div>
    <hr>
</div>
<!-- All users section -->
<section class="first_line">
    <section class="users">
        <h2>Users:</h2>
        <hr>
        <div class="users_section">
            <div class="users_link">
                <a class="btn btn-primary" href="{% url 'dashboard:create_user' %}">Create User</a>
                <a class="btn btn-info" href="{% url 'dashboard:create_user' %}">All Users</a>
            </div>
            <table>
                <tr class="bordered">
                    <th>Users</th>
                    <th>Email</th>
                    <th></th>
                    <hr>
                </tr>
                {% for all in all_users %}
                <tr>
                    <td>{{ all.first_name }}</td>
                    <td>{{ all.email }}</td>
                    <td><a class="btn btn-info" href="#">View</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </section>
    <!-- Messages section -->
    <section class="messages">
        <h2>Messages:</h2>
        <hr>
        <div class="messages_section">
            <a class="btn btn-primary" href="#">Apply Message</a>
            <table>
                <tr class="bordered">
                    <th>Users</th>
                    <th>Type</th>
                    <th></th>
                    <hr>
                </tr>
                {% for y in contact_objects %}
                <tr class="contact_objects">
                    <td>{{ y.your_name }}</td>
                    <td class="category_contact">{{ y.category }}<i class="fa-solid fa-key"></i></td>
                    <td><a class="btn btn-info" href="#">View</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </section>
</section>
<!-- Customers section -->
<section class="customers">
    <h2>Customers:</h2>
    <hr>
    <div class="customers_section">
        <a class="btn btn-primary" href="#">Create Customer</a>
        <table>
            <tr class="bordered">
                <th>Customer</th>
                <th>Email</th>
                <th></th>
                <hr>
            </tr>
            <tr>
                <td>Ahmedov</td>
                <td>husanboy0250@gmail.com</td>
                <td><a style="display: inline; margin-right: 5px;" class="btn btn-info" href="#">View</a><a style="display: inline;" class="btn btn-danger" href="#">Delete</a></td>
            </tr>
        </table>
    </div>
</section>
{% endblock content %}