apps/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
	path("", views.dashboard, name='dashboard_home'),
	path("create-user/", views.create_user, name='create_user')
]

apps/portfolio/urls.py
from django.urls import path, include
from . import views
from apps.authentication.views import signup, login, profile
from django.contrib.auth.views import LogoutView

app_name = 'blog'




urlpatterns = [
    # path('<int:pk>/api-contacts/', views.contact_detail),
    path('api-auth/', include('rest_framework.urls',  namespace='rest_framework')),
    path('', views.home, name='home'),
    path('<int:pk>/post/', views.post, name='post'),
    path('categories/', views.category, name='category'),
    path('category/', views.category_pages, name='category_page'),
    # about us page
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("profile/", profile, name='profile')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.portfolio.urls")),
    path('api/', include("apps.portfolio_api.urls")),
    path('dashboard/', include("apps.dashboard.urls")),
    path('api-auth/', include('rest_framework.urls')),
]


handler404 = "apps.portfolio.views.error_404"
handler500 = "apps.portfolio.views.error_500"

templates/includes/footer.html
{% load static %}
<!-- Footer-->
<footer >
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="https://twitter.com/Husan55400966">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://github.com/hwandev12">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://t.me/galaxy_dev_3">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-brands fa-telegram fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <div class="small text-center text-muted fst-italic">
          Copyright &copy; KhusanAkhmedov 2022
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/loader.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/loader.css' %}">
<!-- about -->
<div class="loader1">
    <div class="about">
        <a class="bg_links social portfolio" href="https://www.rafaelalucas.com" target="_blank">
            <span class="icon"></span>
        </a>
        <a class="bg_links social dribbble" href="https://dribbble.com/rafaelalucas" target="_blank">
            <span class="icon"></span>
        </a>
        <a class="bg_links social linkedin" href="https://www.linkedin.com/in/rafaelalucas/" target="_blank">
            <span class="icon"></span>
        </a>
        <a class="bg_links logo"></a>
    </div>
    <!-- end about -->
    <div class="content_spa loader">
        <div class="planet">
            <div class="ring"></div>
            <div class="cover-ring"></div>
            <div class="spots">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <p>loading</p>
    </div>
</div>
<script>
let loader = document.querySelector(".loader")
let spa = document.querySelector(".about")
let spa1 = document.querySelector(".loader1")
console.log(spa)
window.addEventListener("load", () => {
    loader.classList.add("mariana")
    document.body.classList.add("overflow")
    spa.style.display = "none"
    spa1.style.display = "none"
})
</script>

templates/includes/navigation.html
{% load static %}
<style>
    .navbar {
    display: none !important;
  }
  .anime {
    display: block !important;
  }
  @media(max-width: 992px) {
      a img {
        margin-left: 0px !important;
      }
  }
</style>
<link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
<!-- Font Awesome icons (free version)-->
<script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
<!-- Google fonts-->
<link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
<!-- Core theme CSS (includes Bootstrap)-->
<link href="{% static 'css/styles.css' %}" rel="stylesheet" />
<!-- Navigation-->
<nav style="z-index: 1 !important;" class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5 nav">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Campus</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0 align-items-center">
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:contact' %}">Contact</a>
                </li>
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:login' %}">Login</a>
                </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" id="pop_link" href="#">Logout</a>
                </li>
                {% if request.user.is_organiser %}
                <li class="nav-item">
                    <a class="nav-link" id="pop_link" href="{% url 'dashboard:dashboard_home' %}">Dashboard</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" id="img_profile" href="#"><img style="margin-left: 30px" src="{{ user.profile.image.url }}" alt="" width="30"></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<script>
let nav = document.querySelector(".navbar")
console.log(nav)
window.addEventListener("load", () => {
    nav.classList.add("anime")
})
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>